#ifndef MESSAGE_FILE_TRANSFER_CONTROL_HPP_DEFINED
#define MESSAGE_FILE_TRANSFER_CONTROL_HPP_DEFINED

class MessageFileTransferControl
{
public:
private:
};

#endif // MESSAGE_FILE_TRANSFER_CONTROL_HPP_DEFINED
