name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install build dependencies
      run:
        - ./scripts/install_deps.sh

    - name: Install assets | Download assets
      run: ./scripts/download_assets.sh

    - name: Install assets | Install tools
      run: ./scripts/install_tools.sh

    - name: Install assets | Create spritesheets
      run: ./scripts/create_spritesheets.sh

    - name: Build
      run: make

    - name: Test
      run: make test

    # - name: Run tests
    #   run: make check
      
    # https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html
    # - name: Run distcheck
    #   run: make distcheck
