name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: echo "Install dependencies placeholder"

    - name: Build
      run: make
      
    # - name: Run tests
    #   run: make check
      
    # https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html
    - name: Run distcheck
      run: make distcheck
